const {
  CLIENT_ID,
  GUILD_ID,
  BOT_TOKEN,
  ADMIN_USER_ID,
  DEFAULT_TEXT_CHANNEL,
  INFLUX_URL,
  INFLUX_BUCKET,
  INFLUX_ORG,
  INFLUX_TOKEN,
  WEBSERVER_PORT,
  YOUTUBE_COOKIE,
  YOUTUBE_IDENTITY_TOKEN,
  NOW_PLAYING_MOCK_DATA,
} = process.env

const ENV = {
  CLIENT_ID,
  GUILD_ID,
  BOT_TOKEN,
  ADMIN_USER_ID,
  DEFAULT_TEXT_CHANNEL,
  INFLUX_URL,
  INFLUX_BUCKET,
  INFLUX_ORG,
  INFLUX_TOKEN,
  WEBSERVER_PORT: WEBSERVER_PORT || '8080',
  YOUTUBE_COOKIE: YOUTUBE_COOKIE || '',
  YOUTUBE_IDENTITY_TOKEN,
  NOW_PLAYING_MOCK_DATA: NOW_PLAYING_MOCK_DATA || false,
}

export default ENV
