const {
  CLIENT_ID,
  GUILD_ID,
  BOT_TOKEN,
  ADMIN_USER_ID,
  DEFAULT_TEXT_CHANNEL,
  INFLUX_URL,
  INFLUX_BUCKET,
  INFLUX_ORG,
  INFLUX_TOKEN,
  WEBSERVER_PORT,
  NOW_PLAYING_MOCK_DATA,
  TS_NODE_DEV,
  PRELOAD_SONG_DATA,
  SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET,
  SPOTIFY_MARKET,
  LAVALINK_HOST,
  LAVALINK_PORT,
  LAVALINK_PASSWORD,
  VOICE_COMMANDS_ENABLED,
  VOICE_HELLO_RESPONSES_ENABLED,
  VOICE_WAKE_WORD_CONFIRM_SOUND_ENABLED,
  VOICE_LISTENER_BOT_TOKEN,
  VOSK_MODEL_PATH,
  VOICE_WAKE_PHRASE,
  VOICE_CAPTURE_TIMEOUT_MS,
  VOICE_SILENCE_MS,
  PERF_LOGGING,
  LOG_LEVEL: LOG_LEVEL_ENV,
} = process.env

const logLevels = ['debug', 'info', 'warn', 'error'] as const
const configuredLogLevel = LOG_LEVEL_ENV?.toLowerCase()
const LOG_LEVEL = logLevels.includes(configuredLogLevel as (typeof logLevels)[number])
  ? (configuredLogLevel as (typeof logLevels)[number])
  : 'info'

const ENV = {
  CLIENT_ID,
  GUILD_ID,
  BOT_TOKEN,
  ADMIN_USER_ID,
  DEFAULT_TEXT_CHANNEL,
  INFLUX_URL,
  INFLUX_BUCKET,
  INFLUX_ORG,
  INFLUX_TOKEN,
  TS_NODE_DEV,
  WEBSERVER_PORT: WEBSERVER_PORT || '8080',
  NOW_PLAYING_MOCK_DATA: NOW_PLAYING_MOCK_DATA === 'true',
  PRELOAD_SONG_DATA: PRELOAD_SONG_DATA !== 'false',
  SPOTIFY_CLIENT_ID: SPOTIFY_CLIENT_ID || '',
  SPOTIFY_CLIENT_SECRET: SPOTIFY_CLIENT_SECRET || '',
  SPOTIFY_MARKET: SPOTIFY_MARKET || 'US',
  LAVALINK_HOST: LAVALINK_HOST || 'localhost',
  LAVALINK_PORT: LAVALINK_PORT || '2333',
  LAVALINK_PASSWORD: LAVALINK_PASSWORD || 'youshallnotpass',
  VOICE_COMMANDS_ENABLED: VOICE_COMMANDS_ENABLED === 'true',
  VOICE_HELLO_RESPONSES_ENABLED: VOICE_HELLO_RESPONSES_ENABLED === 'true',
  VOICE_WAKE_WORD_CONFIRM_SOUND_ENABLED: VOICE_WAKE_WORD_CONFIRM_SOUND_ENABLED === 'true',
  VOICE_LISTENER_BOT_TOKEN,
  VOSK_MODEL_PATH: VOSK_MODEL_PATH || './models/vosk-model-small-en-us',
  VOICE_WAKE_PHRASE: VOICE_WAKE_PHRASE || 'castle grooves',
  VOICE_CAPTURE_TIMEOUT_MS: Number(VOICE_CAPTURE_TIMEOUT_MS || 7000),
  VOICE_SILENCE_MS: Number(VOICE_SILENCE_MS || 1200),
  // Disabled by default: timing logs are useful during tuning, but should not add log noise normally.
  PERF_LOGGING: PERF_LOGGING === 'true',
  LOG_LEVEL,
  DEBUG_QUEUE: LOG_LEVEL === 'debug',
}

export default ENV
