name: castle-grooves-dev

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      NODE_ENV: development
      TS_NODE_DEV: 'true'
      ENABLE_DB_WRITES_IN_DEV: ${ENABLE_DB_WRITES_IN_DEV:-false}
      WEBSERVER_PORT: ${WEBSERVER_PORT:-1338}
    ports:
      - '${WEBSERVER_PORT:-1338}:${WEBSERVER_PORT:-1338}'
      - '9229:9229'
    depends_on:
      lavalink:
        condition: service_started
      influxdb:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app
      - ./models:/usr/src/app/models:ro
      - node_modules:/usr/src/app/node_modules
      - yarn_cache:/usr/src/app/.yarn

  lavalink:
    healthcheck:
      disable: true

  influxdb:
    volumes:
      - influxdb-data-dev:/var/lib/influxdb2
      - influxdb-config-dev:/etc/influxdb2

volumes:
  node_modules:
  yarn_cache:
  influxdb-data-dev:
  influxdb-config-dev:
