name: castle-grooves

services:
  bot:
    image: ${DOCKER_HUB_USERNAME}/castle-grooves:latest
    ports:
      - '${WEBSERVER_PORT:-1337}:${WEBSERVER_PORT:-1337}'
    labels:
      com.centurylinklabs.watchtower.enable: 'true'

  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_INCLUDE_RESTARTING: 'true'
      WATCHTOWER_POLL_INTERVAL: '300'
      WATCHTOWER_LABEL_ENABLE: 'true'
      TZ: ${TZ:-America/Toronto}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - castle-grooves
